---
abstract: 'Information about a Git::Repository'
author:
  - 'Nathaniel Nutter <nnutter@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Repository-Plugin-Info
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Git::Repository::Plugin::Info:
    file: lib/Git/Repository/Plugin/Info.pm
    version: 0.03
requires:
  Git::Repository: 1.14
  perl: 5.008005
resources:
  bugtracker: https://github.com/nnutter/Git-Repository-Plugin-Info/issues
  homepage: https://github.com/nnutter/Git-Repository-Plugin-Info
  repository: git://github.com/nnutter/Git-Repository-Plugin-Info.git
version: 0.03
